version: 2.1

workflows:
  test:
    jobs:
      - test-linux:
          name: Ruby 2.4
          docker-image: circleci/ruby:2.4
      - test-linux:
          name: Ruby 2.5
          docker-image: circleci/ruby:2.5
      - test-linux:
          name: Ruby 2.6
          docker-image: circleci/ruby:2.6
      - test-linux:
          name: Ruby 2.7
          docker-image: circleci/ruby:2.7
      - test-linux:
          name: JRuby 9.2
          docker-image: circleci/jruby:9-jdk
          use-jruby-openssl: true

jobs:
  test-linux:
    parameters:
      docker-image:
        type: string
      use-ruby-openssl:
        type: boolean
        default: false
    docker:
      - image: <<parameters.docker-image>>
    steps:
      - checkout
      - when:
          condition: <<parameters.use-jruby-openssl>>
          steps:
            - run: gem install jruby-openssl # required by bundler, no effect on Ruby MRI
      - run: ruby -v
      - run: gem install bundler -v "~> 1.17"
      - run: bundle install
      - run: mkdir ./rspec
      - run: bundle exec rspec --format progress --format RspecJunitFormatter -o ./rspec/rspec.xml spec
      - store_test_results:
          path: ./rspec
      - store_artifacts:
          path: ./rspec
